version: "3"
services:
  luci-cli:
    container_name: luci-cli
    hostname: luci-cli
    build: .
    image: oxr463/luci-cli:latest
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/src/luci-cli/:/usr/src/luci-cli
    working_dir: /usr/src/luci-cli

